# Libraries

In [1]:
import pandas as pd
import numpy as np
import orjson

import tensorflow as tf
from transformers import GPT2Tokenizer, TFGPT2LMHeadModel

# Data preparation

## Data loading

We load the *review* and the *business* json files and transform them into a DataFrame 

In [2]:
with open('data/yelp_academic_dataset_review.json', 'rb') as file:
    reviews = [orjson.loads(line) for line in file]

df_reviews = pd.DataFrame.from_dict(reviews)
df_reviews.head()

review_id                 user_id             business_id  \
0  KU_O5udG6zpxOg-VcAEodg  mh_-eMZ6K5RLWhZyISBhwA  XQfwVwDr-v0ZS3_CbbE5Xw   
1  BiTunyQ73aT9WBnpR9DZGw  OyoGAe7OKpv6SyGZT5g77Q  7ATYjTIgM3jUlt4UM3IypQ   
2  saUsX_uimxRlCVr67Z4Jig  8g_iMtfSiwikVnbP2etR0A  YjUWPpI6HXG530lwP-fb2A   
3  AqPFMleE6RsU23_auESxiA  _7bHUi9Uuf5__HHc_Q8guQ  kxX2SOes4o-D3ZQBkiMRfA   
4  Sx8TMOWLNuJBWer-0pcmoA  bcjbaE6dDog4jkNY91ncLQ  e4Vwtrqf-wpJfwesgvdgxQ   

   stars  useful  funny  cool  \
0    3.0       0      0     0   
1    5.0       1      0     1   
2    3.0       0      0     0   
3    5.0       1      0     1   
4    4.0       1      0     1   

                                                text                 date  
0  If you decide to eat here, just be aware it is...  2018-07-07 22:09:11  
1  I've taken a lot of spin classes over the year...  2012-01-03 15:28:18  
2  Family diner. Had the buffet. Eclectic assortm...  2014-02-05 20:30:30  
3  Wow!  Yummy, different,  delicious.   Our favo...  2015-01-04 00:01:03  
4  Cute interior and owner (?) gave us tour of up...  2017-01-14 20:54:15

In [3]:
with open('data/yelp_academic_dataset_business.json', 'rb') as file:
    business = [orjson.loads(line) for line in file]

df_business = pd.DataFrame.from_dict(business)
df_business.head()

business_id                      name  \
0  Pns2l4eNsfO8kk83dixA6A  Abby Rappoport, LAC, CMQ   
1  mpf3x-BjTdTEA3yCZrAYPw             The UPS Store   
2  tUFrWirKiKi_TAnsVWINQQ                    Target   
3  MTSW4McQd7CbVtyjqoe9mw        St Honore Pastries   
4  mWMc6_wTdE0EUBKIGXDVfA  Perkiomen Valley Brewery   

                           address           city state postal_code  \
0           1616 Chapala St, Ste 2  Santa Barbara    CA       93101   
1  87 Grasso Plaza Shopping Center         Affton    MO       63123   
2             5255 E Broadway Blvd         Tucson    AZ       85711   
3                      935 Race St   Philadelphia    PA       19107   
4                    101 Walnut St     Green Lane    PA       18054   

    latitude   longitude  stars  review_count  is_open  \
0  34.426679 -119.711197    5.0             7        0   
1  38.551126  -90.335695    3.0            15        1   
2  32.223236 -110.880452    3.5            22        0   
3  39.955505  -75.155564    4.0            80        1   
4  40.338183  -75.471659    4.5            13        1   

                                          attributes  \
0                      {'ByAppointmentOnly': 'True'}   
1             {'BusinessAcceptsCreditCards': 'True'}   
2  {'BikeParking': 'True', 'BusinessAcceptsCredit...   
3  {'RestaurantsDelivery': 'False', 'OutdoorSeati...   
4  {'BusinessAcceptsCreditCards': 'True', 'Wheelc...   

                                          categories  \
0  Doctors, Traditional Chinese Medicine, Naturop...   
1  Shipping Centers, Local Services, Notaries, Ma...   
2  Department Stores, Shopping, Fashion, Home & G...   
3  Restaurants, Food, Bubble Tea, Coffee & Tea, B...   
4                          Brewpubs, Breweries, Food   

                                               hours  
0                                               None  
1  {'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ...  
2  {'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ...  
3  {'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ...  
4  {'Wednesday': '14:0-22:0', 'Thursday': '16:0-2...

## Data merge

To get a complete overview of the data, tables are joined by the *business_id* and the variable *stars* is renamed.

In [4]:
df_business = df_business.rename(axis=1, mapper={"stars": "stars_business"})
df_reviews = df_reviews.rename(axis=1, mapper={"stars": "stars_reviews"})
df = pd.merge(df_reviews, df_business, on='business_id')
df.head()

review_id                 user_id             business_id  \
0  KU_O5udG6zpxOg-VcAEodg  mh_-eMZ6K5RLWhZyISBhwA  XQfwVwDr-v0ZS3_CbbE5Xw   
1  VJxlBnJmCDIy8DFG0kjSow  Iaee7y6zdSB3B-kRCo4z1w  XQfwVwDr-v0ZS3_CbbE5Xw   
2  S6pQZQocMB1WHMjTRbt77A  ejFxLGqQcWNLdNByJlIhnQ  XQfwVwDr-v0ZS3_CbbE5Xw   
3  WqgTKVqWVHDHjnjEsBvUgg  f7xa0p_1V9lx53iIGN5Sug  XQfwVwDr-v0ZS3_CbbE5Xw   
4  M0wzFFb7pefOPcxeRVbLag  dCooFVCk8M1nVaQqcfTL3Q  XQfwVwDr-v0ZS3_CbbE5Xw   

   stars_reviews  useful  funny  cool  \
0            3.0       0      0     0   
1            2.0       0      0     0   
2            4.0       2      0     1   
3            3.0       0      0     0   
4            2.0       0      0     0   

                                                text                 date  \
0  If you decide to eat here, just be aware it is...  2018-07-07 22:09:11   
1  This is the second time we tried turning point...  2017-05-13 17:06:55   
2  The place is cute and the staff was very frien...  2017-08-08 00:58:18   
3  We came on a Saturday morning after waiting a ...  2017-11-19 02:20:23   
4  Mediocre at best. The decor is very nice, and ...  2017-09-09 17:49:47   

                           name  ... state postal_code   latitude  longitude  \
0  Turning Point of North Wales  ...    PA       19454  40.210196 -75.223639   
1  Turning Point of North Wales  ...    PA       19454  40.210196 -75.223639   
2  Turning Point of North Wales  ...    PA       19454  40.210196 -75.223639   
3  Turning Point of North Wales  ...    PA       19454  40.210196 -75.223639   
4  Turning Point of North Wales  ...    PA       19454  40.210196 -75.223639   

   stars_business  review_count  is_open  \
0             3.0           169        1   
1             3.0           169        1   
2             3.0           169        1   
3             3.0           169        1   
4             3.0           169        1   

                                          attributes  \
0  {'NoiseLevel': 'u'average'', 'HasTV': 'False',...   
1  {'NoiseLevel': 'u'average'', 'HasTV': 'False',...   
2  {'NoiseLevel': 'u'average'', 'HasTV': 'False',...   
3  {'NoiseLevel': 'u'average'', 'HasTV': 'False',...   
4  {'NoiseLevel': 'u'average'', 'HasTV': 'False',...   

                                          categories  \
0  Restaurants, Breakfast & Brunch, Food, Juice B...   
1  Restaurants, Breakfast & Brunch, Food, Juice B...   
2  Restaurants, Breakfast & Brunch, Food, Juice B...   
3  Restaurants, Breakfast & Brunch, Food, Juice B...   
4  Restaurants, Breakfast & Brunch, Food, Juice B...   

                                               hours  
0  {'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...  
1  {'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...  
2  {'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...  
3  {'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...  
4  {'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...  

[5 rows x 22 columns]

In [11]:
pd.set_option('display.max_columns', None)
df.head()

review_id                 user_id             business_id  \
0  KU_O5udG6zpxOg-VcAEodg  mh_-eMZ6K5RLWhZyISBhwA  XQfwVwDr-v0ZS3_CbbE5Xw   
1  VJxlBnJmCDIy8DFG0kjSow  Iaee7y6zdSB3B-kRCo4z1w  XQfwVwDr-v0ZS3_CbbE5Xw   
2  S6pQZQocMB1WHMjTRbt77A  ejFxLGqQcWNLdNByJlIhnQ  XQfwVwDr-v0ZS3_CbbE5Xw   
3  WqgTKVqWVHDHjnjEsBvUgg  f7xa0p_1V9lx53iIGN5Sug  XQfwVwDr-v0ZS3_CbbE5Xw   
4  M0wzFFb7pefOPcxeRVbLag  dCooFVCk8M1nVaQqcfTL3Q  XQfwVwDr-v0ZS3_CbbE5Xw   

   stars_reviews  useful  funny  cool  \
0            3.0       0      0     0   
1            2.0       0      0     0   
2            4.0       2      0     1   
3            3.0       0      0     0   
4            2.0       0      0     0   

                                                text                 date  \
0  If you decide to eat here, just be aware it is...  2018-07-07 22:09:11   
1  This is the second time we tried turning point...  2017-05-13 17:06:55   
2  The place is cute and the staff was very frien...  2017-08-08 00:58:18   
3  We came on a Saturday morning after waiting a ...  2017-11-19 02:20:23   
4  Mediocre at best. The decor is very nice, and ...  2017-09-09 17:49:47   

                           name              address         city state  \
0  Turning Point of North Wales  1460 Bethlehem Pike  North Wales    PA   
1  Turning Point of North Wales  1460 Bethlehem Pike  North Wales    PA   
2  Turning Point of North Wales  1460 Bethlehem Pike  North Wales    PA   
3  Turning Point of North Wales  1460 Bethlehem Pike  North Wales    PA   
4  Turning Point of North Wales  1460 Bethlehem Pike  North Wales    PA   

  postal_code   latitude  longitude  stars_business  review_count  is_open  \
0       19454  40.210196 -75.223639             3.0           169        1   
1       19454  40.210196 -75.223639             3.0           169        1   
2       19454  40.210196 -75.223639             3.0           169        1   
3       19454  40.210196 -75.223639             3.0           169        1   
4       19454  40.210196 -75.223639             3.0           169        1   

                                          attributes  \
0  {'NoiseLevel': 'u'average'', 'HasTV': 'False',...   
1  {'NoiseLevel': 'u'average'', 'HasTV': 'False',...   
2  {'NoiseLevel': 'u'average'', 'HasTV': 'False',...   
3  {'NoiseLevel': 'u'average'', 'HasTV': 'False',...   
4  {'NoiseLevel': 'u'average'', 'HasTV': 'False',...   

                                          categories  \
0  Restaurants, Breakfast & Brunch, Food, Juice B...   
1  Restaurants, Breakfast & Brunch, Food, Juice B...   
2  Restaurants, Breakfast & Brunch, Food, Juice B...   
3  Restaurants, Breakfast & Brunch, Food, Juice B...   
4  Restaurants, Breakfast & Brunch, Food, Juice B...   

                                               hours  
0  {'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...  
1  {'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...  
2  {'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...  
3  {'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...  
4  {'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'...

## Data filtering

Because the reviews can be for other things than restaurants, only relevant reviews are taken into account.

In [54]:
df = df[df['categories'].str.contains('Restaurants', case=False, na=False)]
df.head()

stars_reviews  stars_business  useful  funny  cool  \
0            3.0             3.0       0      0     0   
1            2.0             3.0       0      0     0   
2            4.0             3.0       2      0     1   
3            3.0             3.0       0      0     0   
4            2.0             3.0       0      0     0   

                                          categories  \
0  Restaurants, Breakfast & Brunch, Food, Juice B...   
1  Restaurants, Breakfast & Brunch, Food, Juice B...   
2  Restaurants, Breakfast & Brunch, Food, Juice B...   
3  Restaurants, Breakfast & Brunch, Food, Juice B...   
4  Restaurants, Breakfast & Brunch, Food, Juice B...   

                                                text  
0  If you decide to eat here, just be aware it is...  
1  This is the second time we tried turning point...  
2  The place is cute and the staff was very frien...  
3  We came on a Saturday morning after waiting a ...  
4  Mediocre at best. The decor is very nice, and ...

## Column selection

Some columns definitely won't be helpfull and we decided to drop them.

In [55]:
cols_to_use = ["stars_reviews", "stars_business", "useful", "funny", "cool", "text"]
df = df.loc[:, cols_to_use]
df.head()

stars_reviews  stars_business  useful  funny  cool  \
0            3.0             3.0       0      0     0   
1            2.0             3.0       0      0     0   
2            4.0             3.0       2      0     1   
3            3.0             3.0       0      0     0   
4            2.0             3.0       0      0     0   

                                                text  
0  If you decide to eat here, just be aware it is...  
1  This is the second time we tried turning point...  
2  The place is cute and the staff was very frien...  
3  We came on a Saturday morning after waiting a ...  
4  Mediocre at best. The decor is very nice, and ...

## Scaling

Stats *funny*, *useful*, and *cool* are rescaled on a $\langle 0,1 \rangle$ range.

In [61]:
df["useful"] = (df["useful"]  - min(df["useful"]))/(max(df["useful"] ) - min(df["useful"]))
df["funny"]  = (df["funny"]   - min(df["funny"]))/ (max(df["funny"] )  - min(df["funny"]))
df["cool"]   = (df["cool"]    - min(df["cool"]))/  (max(df["cool"] )   - min(df["cool"]))
df.head()

stars_reviews  stars_business    useful     funny      cool  \
0            3.0             3.0  0.002375  0.001261  0.002469   
1            2.0             3.0  0.002375  0.001261  0.002469   
2            4.0             3.0  0.007126  0.001261  0.004938   
3            3.0             3.0  0.002375  0.001261  0.002469   
4            2.0             3.0  0.002375  0.001261  0.002469   

                                                text  
0  If you decide to eat here, just be aware it is...  
1  This is the second time we tried turning point...  
2  The place is cute and the staff was very frien...  
3  We came on a Saturday morning after waiting a ...  
4  Mediocre at best. The decor is very nice, and ...

# Transformer

First, the text needs to be encoded.

In [72]:
def format_data(row):
    return f"Metadata: Stars for the review = {row['stars_reviews']}, Stars for the business: {row['stars_business']}, Usefulness = {row['useful']}, Funny: {row['funny']}, Cool: {row['cool']}; Review: {row['text']}"

formatted_text = [format_data(row) for _, row in df.iloc[1:10].iterrows()]

In [95]:
# Initialize the GPT-2 tokenizer and model
model_name = 'gpt2'
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = TFGPT2LMHeadModel.from_pretrained(model_name)

# Tokenize the text data
encoded_texts = [tokenizer(text, return_tensors='tf', max_length=512, truncation=True) for text in formatted_text]

All PyTorch model weights were used when initializing TFGPT2LMHeadModel.

All the weights of TFGPT2LMHeadModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


{'input_ids': <tf.Tensor: shape=(1, 83), dtype=int32, numpy=
array([[ 9171, 14706,    25, 10271,   329,   262,  2423,   796,   604,
           13,    15,    11, 10271,   329,   262,  1597,    25,   513,
           13,    15,    11,  5765, 15538,   796,   362,    11, 40473,
           25,   657,    11, 15226,    25,   352,    11,  6602,    25,
          383,  1295,   318, 13779,   290,   262,  3085,   373,   845,
         8030,    13, 18460,  6859,    13,  4599,   329, 50219,    13,
          775,   550,  9965,   290,   547, 21639,   826,  1497,    13,
          314,  1107,  8359,   262, 40377,   220, 27805,   290,  1735,
          286, 21385,    13, 18460,   284,   423,  1194, 50219,  1295,
         6716,    13]])>, 'attention_mask': <tf.Tensor: shape=(1, 83), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,